# All runtime knobs live here.
[read]
host = "localhost"
port = 3306
socket = "/mnt/vitess/mysql/datadir/mysql.sock"
user = "harness"
password = "HarnessTest!"
workers = 80
iterations = 0
duration = 3600
sleep = 0.0
log_level = "INFO"
log_file = ""
explain = false
show_source_info = false
show_trace = false

[master]
host = "localhost"
port = 3306
socket = "/mnt/vitess/mysql/datadir/mysql.sock"
user = "harness"
password = "HarnessTest!"

[monitor]
enabled = true
dest_root = "/data/percona_monitor"
retention_days = 1
run_seconds = 3600
status_interval_seconds = 60

[defaults]
team_ids = [2981626498, 75899570098, 10736132949, 2151557247, 147557470051, 129325844705, 266105194887, 3022319763812, 463855761557, 1446938121600]
user_id = 900000000001
source_tag = "HARNESS_SMOKE"
metadata_prefix = "harness_smoke"
highlight_type = "harness_smoke"
payload_mode = "random"
payload_file = ""
blob_min_bytes = 512
blob_max_bytes = 262144
reuse_fraction = 0.1
delete_mode = "hard"
delete_target = "inserted"
writer_sleep = 0.0

[insert]
enabled = true
threads = 40
batch_size = 1
sleep = 0.0
team_ids = [2981626498, 75899570098, 10736132949, 2151557247, 147557470051, 129325844705, 266105194887, 3022319763812, 463855761557, 1446938121600]
blob_min_bytes = 512
blob_max_bytes = 262144

[update]
enabled = true
threads = 30
batch_size = 1
sleep = 0.0
columns = ["contents", "contents_highlight", "metadata", "metadata_ekm", "contents_ekm", "contents_highlight_ekm", "external_ptr", "unencrypted_metadata"]
blob_min_bytes = 512
blob_max_bytes = 262144
reuse_fraction = 0.1
team_ids = [2981626498, 75899570098, 10736132949, 2151557247, 147557470051, 129325844705, 266105194887, 3022319763812, 463855761557, 1446938121600]

[delete]
enabled = false
threads = 0
batch_size = 1
sleep = 1.0
mode = "hard"
team_ids = [2981626498, 75899570098, 10736132949, 2151557247, 147557470051, 129325844705, 266105194887, 3022319763812, 463855761557, 1446938121600]
target = "inserted"

[recycle]
enabled = true
threads = 10
batch_size = 4
sleep = 0.0
team_ids = [2981626498, 75899570098, 10736132949, 2151557247, 147557470051, 129325844705, 266105194887, 3022319763812, 463855761557, 1446938121600]
blob_min_bytes = 16384
blob_max_bytes = 262144
metadata_bytes = 48000
teams_shared_with_bytes = 32000
payload_mode = "mixed"
metadata_prefix = "harness_recycle"
source_tag = "HARNESS_RECYCLE"
highlight_type = "harness_recycle"

[crash_queries.core16_recent]
enabled = true
threads = 5
sleep = 0.0
name = "core16_recent"
sql = """
select /*vt+ WORKLOAD_NAME=JobHandlerSlackfillTask:IDRBackfillHandler */ id, team_id, user_id, date_create, secret, pub_secret, size, is_stored, original_name, stored_name, title, mimetype, parent_id, contents, contents_ekm, contents_highlight, contents_highlight_ekm, highlight_type, metadata, metadata_ekm, external_url, is_deleted, date_delete, is_public, pub_shared, last_indexed, source, external_id, service_type_id, service_id, is_multiteam, original_team_id, teams_shared_with, service_team_id, is_tombstoned, thumbnail_version, date_thumbnail_retrieved, external_ptr, md5, metadata_version, unencrypted_metadata, restriction_type, version, weight_string(date_create) from files where team_id = 8865360933815 and is_stored = 0 and date_create > 1597262065 order by files.date_create asc limit 10
"""

[crash_queries.core15_seq]
enabled = true
threads = 5
sleep = 0.0
name = "core15_seq"
sql = """
select /*vt+ ALLOW_SCATTER */ /*vt+ WORKLOAD_NAME=JobHandlerSlackfillTask:IDRBackfillHandler */ id, team_id, user_id, date_create, secret, pub_secret, size, is_stored, original_name, stored_name, title, mimetype, parent_id, contents, contents_ekm, contents_highlight, contents_highlight_ekm, highlight_type, metadata, metadata_ekm, external_url, is_deleted, date_delete, is_public, pub_shared, last_indexed, source, external_id, service_type_id, service_id, is_multiteam, original_team_id, teams_shared_with, service_team_id, is_tombstoned, thumbnail_version, date_thumbnail_retrieved, external_ptr, md5, metadata_version, unencrypted_metadata, restriction_type, version, weight_string(id) from files where team_id = 7594018548 and id > 110863125668 order by files.id asc limit 10
"""

[crash_queries.core14_recent]
enabled = true
threads = 5
sleep = 0.0
name = "core14_recent"
sql = """
select /*vt+ WORKLOAD_NAME=JobHandlerSlackfillTask:IDRBackfillHandler */ id, team_id, user_id, date_create, secret, pub_secret, size, is_stored, original_name, stored_name, title, mimetype, parent_id, contents, contents_ekm, contents_highlight, contents_highlight_ekm, highlight_type, metadata, metadata_ekm, external_url, is_deleted, date_delete, is_public, pub_shared, last_indexed, source, external_id, service_type_id, service_id, is_multiteam, original_team_id, teams_shared_with, service_team_id, is_tombstoned, thumbnail_version, date_thumbnail_retrieved, external_ptr, md5, metadata_version, unencrypted_metadata, restriction_type, version, weight_string(date_create) from files where team_id = 2360670261 and is_stored = 0 and date_create > 1596711908 order by files.date_create asc limit 10
"""

[crash_queries.core13_seq]
enabled = true
threads = 5
sleep = 0.0
name = "core13_seq_ignore"
sql = """
select /*vt+ ALLOW_SCATTER */ /*vt+ WORKLOAD_NAME=JobHandlerSlackfillTask:IDRBackfillHandler */ id, team_id, user_id, date_create, secret, pub_secret, size, is_stored, original_name, stored_name, title, mimetype, parent_id, contents, contents_ekm, contents_highlight, contents_highlight_ekm, highlight_type, metadata, metadata_ekm, external_url, is_deleted, date_delete, is_public, pub_shared, last_indexed, source, external_id, service_type_id, service_id, is_multiteam, original_team_id, teams_shared_with, service_team_id, is_tombstoned, thumbnail_version, date_thumbnail_retrieved, external_ptr, md5, metadata_version, unencrypted_metadata, restriction_type, version, weight_string(id) from files ignore index (`primary`) where team_id = 5042983397 and id > 104816183056 order by files.id asc limit 10 /* xbox_job_execute(JQ_707d97ee6e5cd0e2f481d9aa46091a70): lib_slackfill.hack:1399#IDRBackfillHandler::run() -> lib_data_residency_backfill_handler.hack:48#SensitiveContentBackfillTask::runBackfill() -> lib_ekm_backfill */
"""

[crash_queries.core12_seq]
enabled = true
threads = 5
sleep = 0.0
name = "core12_seq_ignore"
sql = """
select /*vt+ ALLOW_SCATTER */ /*vt+ WORKLOAD_NAME=JobHandlerSlackfillTask:IDRBackfillHandler */ id, team_id, user_id, date_create, secret, pub_secret, size, is_stored, original_name, stored_name, title, mimetype, parent_id, contents, contents_ekm, contents_highlight, contents_highlight_ekm, highlight_type, metadata, metadata_ekm, external_url, is_deleted, date_delete, is_public, pub_shared, last_indexed, source, external_id, service_type_id, service_id, is_multiteam, original_team_id, teams_shared_with, service_team_id, is_tombstoned, thumbnail_version, date_thumbnail_retrieved, external_ptr, md5, metadata_version, unencrypted_metadata, restriction_type, version, weight_string(id) from files ignore index (`primary`) where team_id = 7366884189553 and id > 4385210107 order by files.id asc limit 10 /* xbox_job_execute(JQ_2061f7949eabb927f447ad161eeebe4f): lib_slackfill.hack:1399#IDRBackfillHandler::run() -> lib_data_residency_backfill_handler.hack:48#SensitiveContentBackfillTask::runBackfill() -> lib_ekm_backfil */
"""
