CREATE TABLE IF NOT EXISTS `files` (
  `id` bigint unsigned NOT NULL,
  `team_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `date_create` int unsigned NOT NULL,
  `secret` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `pub_secret` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `size` bigint unsigned NOT NULL DEFAULT '0',
  `is_stored` tinyint unsigned NOT NULL DEFAULT '0',
  `original_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `stored_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `mimetype` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `parent_id` bigint unsigned NOT NULL DEFAULT '0',
  `contents` mediumblob NOT NULL,
  `contents_ekm` longblob,
  `contents_highlight` mediumblob NOT NULL,
  `contents_highlight_ekm` longblob,
  `highlight_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `metadata` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `metadata_ekm` longblob,
  `external_url` varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0',
  `date_delete` int unsigned NOT NULL DEFAULT '0',
  `is_public` tinyint unsigned NOT NULL DEFAULT '0',
  `pub_shared` tinyint unsigned NOT NULL DEFAULT '0',
  `last_indexed` int unsigned NOT NULL DEFAULT '0',
  `source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `external_id` varchar(4096) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `service_type_id` int DEFAULT '0',
  `service_id` bigint unsigned NOT NULL DEFAULT '0',
  `is_multiteam` tinyint unsigned NOT NULL DEFAULT '0',
  `original_team_id` bigint unsigned NOT NULL DEFAULT '0',
  `teams_shared_with` text CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `service_team_id` bigint unsigned NOT NULL DEFAULT '0',
  `is_tombstoned` tinyint unsigned NOT NULL DEFAULT '0',
  `thumbnail_version` bigint unsigned NOT NULL DEFAULT '0',
  `date_thumbnail_retrieved` int unsigned NOT NULL DEFAULT '0',
  `external_ptr` blob,
  `md5` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `metadata_version` tinyint NOT NULL DEFAULT '0',
  `unencrypted_metadata` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `restriction_type` tinyint unsigned NOT NULL DEFAULT '0',
  `version` bigint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `team_id_2` (`team_id`,`is_deleted`,`is_public`,`date_create`),
  KEY `team_id_3` (`team_id`,`is_deleted`,`is_public`,`user_id`,`date_create`),
  KEY `team_id_4` (`team_id`,`date_create`),
  KEY `team_id_5` (`team_id`,`is_deleted`,`external_id`(191)),
  KEY `team_id_6` (`team_id`,`date_delete`,`is_public`,`date_create`),
  KEY `team_id_7` (`team_id`,`date_delete`,`is_public`,`user_id`,`date_create`),
  KEY `team_id_8` (`team_id`,`date_delete`,`external_id`(191)),
  KEY `user_and_team` (`user_id`,`team_id`),
  KEY `team_id_date_thumbnail_retrieved` (`team_id`,`date_thumbnail_retrieved`),
  KEY `team_id` (`team_id`,`external_url`(191),`date_create`),
  KEY `highlight_type_team_id` (`highlight_type`,`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPRESSED;
